### ISSUE TITLE
Encoded Characters Missing

### ISSUE THREAD

**Issue by jmbarne3** [UCF/PostMaster#139]
**Describe the bug**
A user reported that their name was being misspelled when receiving emails. The news email in question uses the "Preferred Name" attribute within the email. Upon receiving the email, the user's name, "Renée", would be missing the "é" (e acute) and would be spelled "Rene".

We need to look into if it's the substitution process that is throwing out the character, if the character it simply being removed at some point along the way due to an encoding change, or if the character is present and it's possibly a problem on the client software the user is using.

**Steps to Reproduce**

1. Prepare an email with an attribute substitute, like "Preferred Name".
2. Send the email to a recipient who has an e acute within the attribute being used.

**Expected Behavior**
The email should include the various encoded character's in the email.

**Comment by cjg89** [comment]
Noting here for reference--unfortunately, changes included in #143 and #144 _do not_ appear to solve this problem (tested in QA).

**Comment by cjg89** [comment]
This is almost certainly being caused by this line: https://github.com/UCF/PostMaster/blob/master/manager/models.py#L57
