### ISSUE TITLE
Black Bar Preview inserts a space before the closing </a> tag

### ISSUE THREAD

**Issue by cadie** [UCF/PostMaster#45]
The preview that goes out 1 hour before an email sends, adds a space before `</a>`:
![Screen Shot 2019-08-01 at 4 05 13 PM](https://user-images.githubusercontent.com/21267784/62323834-2b78fa00-b476-11e9-8472-a6664558a0c3.png)

Instant send emails do not have this issue nor do the final emails that are sent.

**Comment by cjg89** [comment]
Haven't tested this, but my theory is that this is occurring here (`soup.prettify()`):
https://github.com/UCF/PostMaster/blob/9117f5c7634657680637d0640a4319ea0c08b36a/manager/models.py#L547
Email clients like Outlook probably don't handle additional whitespace added between the start/end `<a>` tags particularly well: https://www.crummy.com/software/BeautifulSoup/bs4/doc/index.html#pretty-printing

We should use a non-pretty (ugly?) method of getting a string value from BeautifulSoup instead (see "Non-pretty printing" in the link above)
