### ISSUE TITLE
Create functionality to create new recipient groups for resending an email to recipients who did not click anything in the email or did not open the email

### ISSUE THREAD

**Issue by rogerwolf** [UCF/PostMaster#46]
For emails that have a specific call to action (surveys, invitations, donations, etc), we'd like to be able to quickly get a recipient group constructed from 1. everyone who didn't open the email and 2. everyone who didn't click on anything in the email. 

Once we have those stored as new recipient groups, we'll be able to target those users with a follow up but not send an extra email to someone who has already clicked-through/converted.

**Comment by jmbarne3** [comment]
Are we looking to create groups that didn't open _and_ didn't click, or just one of them? Or would it better to design the interface to be either or, i.e. use checkboxes that act as filters and then creates the recipient group based on the filters?

**Comment by jmbarne3** [comment]
Added in v2.3.0. merged in #58
