### ISSUE TITLE
URLClick Duplicates

### ISSUE THREAD

**Issue by jmbarne3** [UCF/PostMaster#98]
**Describe the bug**
URLClicks are only supposed to be recorded once per recipient. Update the following lines: https://github.com/UCF/PostMaster/blob/master/manager/views.py#L1040-L1041 to use the `get_or_create` function to ensure only one instance per recipient is getting created.

**Expected Behavior**
One click per recipient.

**Possible Fix**
Read above.

**Comment by cjg89** [comment]
Resolved in v3.0.2.
